blueprint:
  name: "plate01 Remove HASP MQTT discovery messages"
  description: "Press EXECUTE to remove retained MQTT discovery messages for a decommissioned HASP"
  source_url: "https://github.com/aderusha/HASwitchPlate/blob/master/Home_Assistant/blueprints/automation/hasp_Remove_MQTT_Discovery_Devices.yaml"
  domain: automation
  input:
    haspname:
      name: "HASP device name to remove"
      description: "Enter the name of the HASP device to remove the MQTT discovery messages"

mode: single
max_exceeded: silent

variables:
  haspname: !input haspname

trigger: []

action:
  - service: mqtt.publish
    data_template:
      topic: "hasp/{{haspname}}/status"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "hasp/{{haspname}}/command"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "hasp/{{haspname}}/command/page"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "hasp/{{haspname}}/state/page"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "hasp/{{haspname}}/sensor"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "hasp/{{haspname}}/light/state"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "hasp/{{haspname}}/brightness/state"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "homeassistant/binary_sensor/{{haspname}}/config"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "homeassistant/light/{{haspname}}/config"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "homeassistant/sensor/{{haspname}}/config"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "homeassistant/number/{{haspname}}/config"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "homeassistant/light/{{haspname}}/selectedforegroundcolor/config"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "homeassistant/light/{{haspname}}/selectedbackgroundcolor/config"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "homeassistant/light/{{haspname}}/unselectedforegroundcolor/config"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "homeassistant/light/{{haspname}}/unselectedbackgroundcolor/config"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "hasp/{{haspname}}/light/selectedforegroundcolor/switch"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "hasp/{{haspname}}/light/selectedforegroundcolor/rgb"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "hasp/{{haspname}}/light/selectedbackgroundcolor/switch"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "hasp/{{haspname}}/light/selectedbackgroundcolor/rgb"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "hasp/{{haspname}}/light/unselectedforegroundcolor/switch"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "hasp/{{haspname}}/light/unselectedforegroundcolor/rgb"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "hasp/{{haspname}}/light/unselectedbackgroundcolor/switch"
      payload: ""
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "hasp/{{haspname}}/light/unselectedbackgroundcolor/rgb"
      payload: ""
      retain: true
