##############################################################################
# Automations for handling Scene select buttons on page 1

automation:
  # Set font and text labels for scene buttons on device connection
  - alias: hasp_plate01_p1_ScenesInit
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/status'
      payload: 'ON'
    action:
    - service: python_script.hasp_update_message
      data:
        node_name: plate01
        object_id: 'p[1].b[4]'
        text: 'Lights On'
    - service: python_script.hasp_update_message
      data:
        node_name: plate01
        object_id: 'p[1].b[5]'
        text: 'Daylight'
    - service: python_script.hasp_update_message
      data:
        node_name: plate01
        object_id: 'p[1].b[6]'
        text: 'Night'
    - service: python_script.hasp_update_message
      data:
        node_name: plate01
        object_id: 'p[1].b[7]'
        text: 'Lights Off'

  # Trigger scene.lights_on when p[1].b[4] pressed
  - alias: hasp_plate01_p1_SceneButton4
    trigger:
      platform: mqtt
      topic: 'hasp/plate01/state/p[1].b[4]'
      payload: 'ON'
    action:
      service: scene.turn_on
      entity_id: scene.lights_on

  # Trigger scene.daylight when p[1].b[5] pressed
  - alias: hasp_plate01_p1_SceneButton5
    trigger:
      platform: mqtt
      topic: 'hasp/plate01/state/p[1].b[5]'
      payload: 'ON'
    action:
      service: scene.turn_on
      entity_id: scene.daylight

  # Trigger scene.night when p[1].b[6] pressed
  - alias: hasp_plate01_p1_SceneButton6
    trigger:
      platform: mqtt
      topic: 'hasp/plate01/state/p[1].b[6]'
      payload: 'ON'
    action:
      service: scene.turn_on
      entity_id: scene.night

  # Trigger lights_off.night when p[1].b[7] pressed
  - alias: hasp_plate01_p1_SceneButton7
    trigger:
      platform: mqtt
      topic: 'hasp/plate01/state/p[1].b[7]'
      payload: 'ON'
    action:
      service: scene.turn_on
      entity_id: scene.lights_off
