##############################################################################
# Automations for handling fan controls on page 10
automation:
  - alias: hasp_plate01_p10_FanInit
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate01_connected"
        to: "on"
      - platform: homeassistant
        event: start
    action:
      # Set text, font, and justification for the buttons
      - service: mqtt.publish
        data:
          topic: "hasp/plate01/command/json"
          payload_template: >-
            ["p[10].b[4].font=7","p[10].b[4].xcen=2","p[10].b[5].font=7","p[10].b[6].font=7","p[10].b[7].font=7","p[10].b[8].font=7",
            "p[10].b[4].txt=\"Fan Light \"","p[10].b[5].txt=\"Off\"","p[10].b[6].txt=\"Low\"","p[10].b[7].txt=\"Med\"","p[10].b[8].txt=\"High\""]

  # Toggle light1 when p[10].b[4] pressed
  - alias: hasp_plate01_p10_ToggleLight1
    trigger:
      - platform: mqtt
        topic: "hasp/plate01/state/p[10].b[4]"
        payload: "ON"
    action:
      - service: homeassistant.toggle
        entity_id: light.light_1

  - alias: hasp_plate01_p10_SendFanModeOff
    trigger:
      - platform: mqtt
        topic: "hasp/plate01/state/p[10].b[5]"
        payload: "ON"
    action:
      - service: fan.turn_off
        entity_id: fan.mqtt_fan
      - service: fan.set_speed
        entity_id: fan.mqtt_fan
        data:
          speed: "off"

  - alias: hasp_plate01_p10_SendFanModeLow
    trigger:
      - platform: mqtt
        topic: "hasp/plate01/state/p[10].b[6]"
        payload: "ON"
    action:
      - service: fan.turn_on
        entity_id: fan.mqtt_fan
      - service: fan.set_speed
        entity_id: fan.mqtt_fan
        data:
          speed: "low"

  - alias: hasp_plate01_p10_SendFanModeMedium
    trigger:
      - platform: mqtt
        topic: "hasp/plate01/state/p[10].b[7]"
        payload: "ON"
    action:
      - service: fan.turn_on
        entity_id: fan.mqtt_fan
      - service: fan.set_speed
        entity_id: fan.mqtt_fan
        data:
          speed: "medium"

  - alias: hasp_plate01_p10_SendFanModeHigh
    trigger:
      - platform: mqtt
        topic: "hasp/plate01/state/p[10].b[8]"
        payload: "ON"
    action:
      - service: fan.turn_on
        entity_id: fan.mqtt_fan
      - service: fan.set_speed
        entity_id: fan.mqtt_fan
        data:
          speed: "high"

  - alias: hasp_plate01_p10_UpdateFanModeOff
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate01_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: template
        value_template: "{{ is_state_attr('fan.mqtt_fan', 'speed', 'off') }}"
      - platform: state
        entity_id: "fan.mqtt_fan"
        to: "off"
    condition:
      - condition: template
        value_template: "{{ is_state_attr('fan.mqtt_fan', 'speed', 'off') }}"
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/plate01/command/json"
          payload_template: >-
            ["p[10].b[5].pco={{ states('input_number.hasp_plate01_selectedforegroundcolor')|int }}",
            "p[10].b[5].bco={{ states('input_number.hasp_plate01_selectedbackgroundcolor')|int }}",
            "p[10].b[6].pco={{ states('input_number.hasp_plate01_unselectedforegroundcolor')|int }}",
            "p[10].b[6].bco={{ states('input_number.hasp_plate01_unselectedbackgroundcolor')|int }}",
            "p[10].b[7].pco={{ states('input_number.hasp_plate01_unselectedforegroundcolor')|int }}",
            "p[10].b[7].bco={{ states('input_number.hasp_plate01_unselectedbackgroundcolor')|int }}",
            "p[10].b[8].pco={{ states('input_number.hasp_plate01_unselectedforegroundcolor')|int }}",
            "p[10].b[8].bco={{ states('input_number.hasp_plate01_unselectedbackgroundcolor')|int }}"]

  - alias: hasp_plate01_p10_UpdateFanModeLow
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate01_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: template
        value_template: "{{ is_state_attr('fan.mqtt_fan', 'speed', 'low') }}"
      - platform: state
        entity_id: "fan.mqtt_fan"
        to: "on"
    condition:
      - condition: template
        value_template: "{{ is_state_attr('fan.mqtt_fan', 'speed', 'low') }}"
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/plate01/command/json"
          payload_template: >-
            ["p[10].b[5].pco={{ states('input_number.hasp_plate01_unselectedforegroundcolor')|int }}",
            "p[10].b[5].bco={{ states('input_number.hasp_plate01_unselectedbackgroundcolor')|int }}",
            "p[10].b[6].pco={{ states('input_number.hasp_plate01_selectedforegroundcolor')|int }}",
            "p[10].b[6].bco={{ states('input_number.hasp_plate01_selectedbackgroundcolor')|int }}",
            "p[10].b[7].pco={{ states('input_number.hasp_plate01_unselectedforegroundcolor')|int }}",
            "p[10].b[7].bco={{ states('input_number.hasp_plate01_unselectedbackgroundcolor')|int }}",
            "p[10].b[8].pco={{ states('input_number.hasp_plate01_unselectedforegroundcolor')|int }}",
            "p[10].b[8].bco={{ states('input_number.hasp_plate01_unselectedbackgroundcolor')|int }}"]

  - alias: hasp_plate01_p10_UpdateFanModeMedium
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate01_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: template
        value_template: "{{ is_state_attr('fan.mqtt_fan', 'speed', 'medium') }}"
      - platform: state
        entity_id: "fan.mqtt_fan"
        to: "on"
    condition:
      - condition: template
        value_template: "{{ is_state_attr('fan.mqtt_fan', 'speed', 'medium') }}"
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/plate01/command/json"
          payload_template: >-
            ["p[10].b[5].pco={{ states('input_number.hasp_plate01_unselectedforegroundcolor')|int }}",
            "p[10].b[5].bco={{ states('input_number.hasp_plate01_unselectedbackgroundcolor')|int }}",
            "p[10].b[6].pco={{ states('input_number.hasp_plate01_unselectedforegroundcolor')|int }}",
            "p[10].b[6].bco={{ states('input_number.hasp_plate01_unselectedbackgroundcolor')|int }}",
            "p[10].b[7].pco={{ states('input_number.hasp_plate01_selectedforegroundcolor')|int }}",
            "p[10].b[7].bco={{ states('input_number.hasp_plate01_selectedbackgroundcolor')|int }}",
            "p[10].b[8].pco={{ states('input_number.hasp_plate01_unselectedforegroundcolor')|int }}",
            "p[10].b[8].bco={{ states('input_number.hasp_plate01_unselectedbackgroundcolor')|int }}"]

  - alias: hasp_plate01_p10_UpdateFanModeHigh
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate01_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: template
        value_template: "{{ is_state_attr('fan.mqtt_fan', 'speed', 'high') }}"
      - platform: state
        entity_id: "fan.mqtt_fan"
        to: "on"
    condition:
      - condition: template
        value_template: "{{ is_state_attr('fan.mqtt_fan', 'speed', 'high') }}"
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/plate01/command/json"
          payload_template: >-
            ["p[10].b[5].pco={{ states('input_number.hasp_plate01_unselectedforegroundcolor')|int }}",
            "p[10].b[5].bco={{ states('input_number.hasp_plate01_unselectedbackgroundcolor')|int }}",
            "p[10].b[6].pco={{ states('input_number.hasp_plate01_unselectedforegroundcolor')|int }}",
            "p[10].b[6].bco={{ states('input_number.hasp_plate01_unselectedbackgroundcolor')|int }}",
            "p[10].b[7].pco={{ states('input_number.hasp_plate01_unselectedforegroundcolor')|int }}",
            "p[10].b[7].bco={{ states('input_number.hasp_plate01_unselectedbackgroundcolor')|int }}",
            "p[10].b[8].pco={{ states('input_number.hasp_plate01_selectedforegroundcolor')|int }}",
            "p[10].b[8].bco={{ states('input_number.hasp_plate01_selectedbackgroundcolor')|int }}"]

  - alias: hasp_plate01_p10_FanLightOnColor
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate01_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: "light.light_1"
        to: "on"
    condition:
      - condition: state
        entity_id: "light.light_1"
        state: "on"
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/plate01/command/json"
          payload_template: >-
            ["p[10].b[4].pco={{ states('input_number.hasp_plate01_selectedforegroundcolor')|int }}",
            "p[10].b[4].bco={{ states('input_number.hasp_plate01_selectedbackgroundcolor')|int }}"]

  - alias: hasp_plate01_p10_FanLightOffColor
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate01_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: "light.light_1"
        to: "off"
    condition:
      - condition: state
        entity_id: "light.light_1"
        state: "off"
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/plate01/command/json"
          payload_template: >-
            ["p[10].b[4].pco={{ states('input_number.hasp_plate01_unselectedforegroundcolor')|int }}",
            "p[10].b[4].bco={{ states('input_number.hasp_plate01_unselectedbackgroundcolor')|int }}"]

  - alias: hasp_plate01_p10_FanLightOnIcon
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate01_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: "light.light_1"
        to: "on"
      - platform: mqtt
        topic: "hasp/plate01/command/page"
        payload: "10"
      - platform: mqtt
        topic: "hasp/plate01/state/p[10].b[4]"
        payload: "OFF"
      - platform: state
        entity_id: input_number.hasp_plate01_selectedbackgroundcolor
      - platform: state
        entity_id: input_number.hasp_plate01_unselectedbackgroundcolor
      - platform: state
        entity_id: input_number.hasp_plate01_selectedforegroundcolor
      - platform: state
        entity_id: input_number.hasp_plate01_unselectedforegroundcolor
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ (states('input_number.hasp_plate01_activepage')|int) == 10 }}"
        - condition: state
          entity_id: "light.light_1"
          state: "on"
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/plate01/command/json"
          payload: '["delay 1","xstr 5,15,55,65,8,65280,0,1,1,3,\"\""]'

  - alias: hasp_plate01_p10_FanLightOffIcon
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate01_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: "light.light_1"
        to: "off"
      - platform: mqtt
        topic: "hasp/plate01/command/page"
        payload: "10"
      - platform: mqtt
        topic: "hasp/plate01/state/p[10].b[4]"
        payload: "OFF"
      - platform: state
        entity_id: input_number.hasp_plate01_selectedbackgroundcolor
      - platform: state
        entity_id: input_number.hasp_plate01_unselectedbackgroundcolor
      - platform: state
        entity_id: input_number.hasp_plate01_selectedforegroundcolor
      - platform: state
        entity_id: input_number.hasp_plate01_unselectedforegroundcolor
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ (states('input_number.hasp_plate01_activepage')|int) == 10 }}"
        - condition: state
          entity_id: "light.light_1"
          state: "off"
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/plate01/command/json"
          payload_template: >-
            ["delay 1","xstr 5,15,55,65,8,{{ states('input_number.hasp_plate01_unselectedforegroundcolor')|int }},0,1,1,3,\"\""]

  ##############################################################################
  # Automations to set colors on HASP Page 10
  #
  - alias: hasp_plate01_p10_ColorConfig_selectedforegroundcolor
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate01_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: input_number.hasp_plate01_selectedforegroundcolor
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/plate01/command/json"
          payload_template: >-
            [{%- for i in range(4,9) -%}"p[10].b[{{i}}].pco={{ states('input_number.hasp_plate01_selectedforegroundcolor')|int }}"{% if not loop.last %},{% endif %}{%- endfor -%}]

  - alias: hasp_plate01_p10_ColorConfig_selectedbackgroundcolor
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate01_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: input_number.hasp_plate01_selectedbackgroundcolor
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/plate01/command/json"
          payload_template: >-
            [{%- for i in range(4,9) -%}"p[10].b[{{i}}].bco={{ states('input_number.hasp_plate01_selectedbackgroundcolor')|int }}"{% if not loop.last %},{% endif %}{%- endfor -%}]

  - alias: hasp_plate01_p10_ColorConfig_unselectedforegroundcolor
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate01_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: input_number.hasp_plate01_unselectedforegroundcolor
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/plate01/command/json"
          payload_template: >-
            [{%- for i in range(4,9) -%}"p[10].b[{{i}}].pco2={{ states('input_number.hasp_plate01_unselectedforegroundcolor')|int }}"{% if not loop.last %},{% endif %}{%- endfor -%}]

  - alias: hasp_plate01_p10_ColorConfig_unselectedbackgroundcolor
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate01_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: input_number.hasp_plate01_unselectedbackgroundcolor
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/plate01/command/json"
          payload_template: >-
            [{%- for i in range(4,9) -%}"p[10].b[{{i}}].bco2={{ states('input_number.hasp_plate01_unselectedbackgroundcolor')|int }}"{% if not loop.last %},{% endif %}{%- endfor -%}]
