##############################################################################
# Automations to configure slider controls on page 4 as light dimmers
automation:
  - alias: hasp_plate01_p4_DimmersInit
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/status'
      payload: 'ON'
    action:
    - service: python_script.hasp_update_message
      data:
        nodename: plate01
        object_id: 'p[4].b[4]'
        text: 'Light 1'
    - service: python_script.hasp_update_message
      data:
        nodename: plate01
        object_id: 'p[4].b[5]'
        text: 'Light 2'
    - service: python_script.hasp_update_message
      data:
        nodename: plate01
        object_id: 'p[4].b[6]'
        text: 'Light 3'

  - alias: hasp_plate01_p4_Dimmer7UpdateHass
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[4].b[7].val'
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.light_1
        brightness: '{{ trigger.payload }}'

  - alias: hasp_plate01_p4_Dimmer7UpdateHASP
    trigger:
    - platform: state
      entity_id: light.light_1
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[4].b[7].val'
        payload_template: '{{states.light.light_1.attributes.brightness|default(0)|int}}'

  - alias: hasp_plate01_p4_Dimmer8UpdateHass
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[4].b[8].val'
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.light_2
        brightness: '{{ trigger.payload }}'

  - alias: hasp_plate01_p4_Dimmer8UpdateHASP
    trigger:
    - platform: state
      entity_id: light.light_2
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[4].b[8].val'
        payload_template: '{{states.light.light_2.attributes.brightness|default(0)|int}}'

  - alias: hasp_plate01_p4_Dimmer9UpdateHass
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[4].b[9].val'
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.light_3
        brightness: '{{ trigger.payload }}'

  - alias: hasp_plate01_p4_Dimmer9UpdateHASP
    trigger:
    - platform: state
      entity_id: light.light_3
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[4].b[9].val'
        payload_template: '{{states.light.light_3.attributes.brightness|default(0)|int}}'
