##############################################################################
# Automations for handling toggle state buttons on page 3
automation:
  # Set font and text for toggle buttons on device connection
  - alias: hasp_plate01_p3_ToggleInit
    trigger:
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[4].font'
        payload: '2'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[4].txt'
        payload: '"Light 1"'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[5].font'
        payload: '2'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[5].txt'
        payload: '"Light 2"'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[6].font'
        payload: '2'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[6].txt'
        payload: '"Light 3"'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[7].font'
        payload: '2'

  # Toggle light1 when p[3].b[4] pressed
  - alias: hasp_plate01_p3_ToggleLight1
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[3].b[4]'
      payload: 'ON'
    action:
    - service: homeassistant.toggle
      entity_id: light.light_1
      
  # Toggle light2 when p[3].b[5] pressed
  - alias: hasp_plate01_p3_ToggleLight2
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[3].b[5]'
      payload: 'ON'
    action:
    - service: homeassistant.toggle
      entity_id: light.light_2

  # Toggle light3 when p[3].b[6] pressed
  - alias: hasp_plate01_p3_ToggleLight3
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[3].b[6]'
      payload: 'ON'
    action:
    - service: homeassistant.toggle
      entity_id: light.light_3

  # Toggle all light_toggle_group when p[3].b[7] pressed
  - alias: hasp_plate01_p3_ToggleAll
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[3].b[7]'
      payload: 'ON'
    action:
    - service_template: >
          {% if states.group.light_toggle_group.state == "on" -%}
            homeassistant.turn_off
          {%- else -%}
            homeassistant.turn_on
          {%- endif %}
      entity_id: group.light_toggle_group
      
  # Toggle colors on p[3].b[4] when light1 changes
  - alias: hasp_plate01_p3_ToggleColor1
    trigger:
    - platform: state
      entity_id: light.light_1
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_plate01_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[4].bco'
        payload_template: >-
          {% if states.light.light_1.state == "on" -%}
            {{ states.input_number.hasp_plate01_selectedbackgroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_plate01_unselectedbackgroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[3].b[4].pco'
        payload_template: >-
          {% if states.light.light_1.state == "on" -%}
            {{ states.input_number.hasp_plate01_selectedforegroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_plate01_unselectedforegroundcolor.state | int }}
          {%- endif %}

  # Toggle colors on p[3].b[5] when light1 changes
  - alias: hasp_plate01_p3_ToggleColor2
    trigger:
    - platform: state
      entity_id: light.light_2
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_plate01_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[5].bco'
        payload_template: >-
          {% if states.light.light_2.state == "on" -%}
            {{ states.input_number.hasp_plate01_selectedbackgroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_plate01_unselectedbackgroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[3].b[5].pco'
        payload_template: >-
          {% if states.light.light_2.state == "on" -%}
            {{ states.input_number.hasp_plate01_selectedforegroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_plate01_unselectedforegroundcolor.state | int }}
          {%- endif %}

  # Toggle colors on p[3].b[6] when light1 changes
  - alias: hasp_plate01_p3_ToggleColor3
    trigger:
    - platform: state
      entity_id: light.light_3
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_plate01_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[6].bco'
        payload_template: >-
          {% if states.light.light_3.state == "on" -%}
            {{ states.input_number.hasp_plate01_selectedbackgroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_plate01_unselectedbackgroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[3].b[6].pco'
        payload_template: >-
          {% if states.light.light_3.state == "on" -%}
            {{ states.input_number.hasp_plate01_selectedforegroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_plate01_unselectedforegroundcolor.state | int }}
          {%- endif %}

  # Set button 4 to "All Off" if any lights are on, otherwise set to "All On"
  - alias: hasp_plate01_p3_ToggleColorAll
    trigger:
    - platform: state
      entity_id: group.light_toggle_group
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_plate01_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[7].bco'
        payload_template: >-
          {% if states.group.light_toggle_group.state == "on" -%}
            {{ states.input_number.hasp_plate01_unselectedbackgroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_plate01_selectedbackgroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[3].b[7].pco'
        payload_template: >-
          {% if states.group.light_toggle_group.state == "on" -%}
            {{ states.input_number.hasp_plate01_unselectedforegroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_plate01_selectedforegroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[3].b[7].txt'
        payload_template: >-
          {% if states.group.light_toggle_group.state == "on" -%}
           "Lights Off"
          {%- else -%}
           "Lights On"
          {%- endif %}