###############################################################################
# set key labels at system start
- alias: HASwitchPlate_Page7_AlarmCodeKeyLabels
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[4].txt'
      payload: '"1"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[5].txt'
      payload: '"2"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[6].txt'
      payload: '"3"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[7].txt'
      payload: '"4"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[8].txt'
      payload: '"5"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[9].txt'
      payload: '"6"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[10].txt'
      payload: '"7"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[11].txt'
      payload: '"8"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[12].txt'
      payload: '"9"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[14].txt'
      payload: '"0"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[4].font'
      payload: '3'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[5].font'
      payload: '3'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[6].font'
      payload: '3'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[7].font'
      payload: '3'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[8].font'
      payload: '3'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[9].font'
      payload: '3'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[10].font'
      payload: '3'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[11].font'
      payload: '3'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[12].font'
      payload: '3'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[13].font'
      payload: '0'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[14].font'
      payload: '3'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[15].font'
      payload: '0'

# set key labels at system start when system is disarmed, or when switching to disarmed
- alias: HASwitchPlate_Page7_AlarmCodeKeyLabelDisarmed
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: 'disarmed'
  condition: 
    condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: 'disarmed'
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[13].txt'
      payload: '"DIS\rARMED"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[13].font'
      payload: '0'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[13].pco'
      payload: '63488'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[13].bco'
      payload: '65535'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[15].txt'
      payload: '"ARM"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[15].font'
      payload: '1'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[15].pco'
      payload: '65535'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[15].bco'
      payload: '63488'

# set key labels at system start when system is armed_away, or when switching to armed_away
- alias: HASwitchPlate_Page7_AlarmCodeKeyLabelArmed
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: 'armed_away'
  condition: 
    condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: 'armed_away'
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[13].txt'
      payload: '"ARMED"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[13].font'
      payload: '0'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[13].pco'
      payload: '65535'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[13].bco'
      payload: '63488'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[15].txt'
      payload: '"DISARM"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[15].font'
      payload: '0'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[13].pco'
      payload: '63488'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[13].bco'
      payload: '65535'
###############################################################################     
      
# This automation catches the key presses 1-9 and sets our input numbers in response.
# Button p[7]b[4] is labeled 1, so I'm grabbing buttons p[7]b[4] through p[7]b[13]
# then subtracting 3.  The math doesn't work out for button "0" so that will be handled
# in a separate automation.  Once we have the button number, we can copy slider 2 to 1,
# 3 to 2, 4 to 3, then set our new value into slider 4 to update our rolling code entry.
- alias: HASwitchPlate_AlarmCodeEntry_1to9
  trigger:
  - platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/+'
    payload: 'OFF'
  condition: 
    condition: template
    value_template: '{{ (trigger.topic.split("/")[-1].split("p[")[1].split("]")[0]|int == 7) and ( 4 <= trigger.topic.split("/")[-1].split("].b[")[1].strip("]")|int <= 12) }}'
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.haswitchplate_alarmcode1
      value: '{{ states.input_number.haswitchplate_alarmcode2.state }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.haswitchplate_alarmcode2
      value: '{{ states.input_number.haswitchplate_alarmcode3.state }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.haswitchplate_alarmcode3
      value: '{{ states.input_number.haswitchplate_alarmcode4.state }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.haswitchplate_alarmcode4
      value: '{{trigger.topic.split("/")[-1].split("].b[")[1].strip("]")|int-3}}'

- alias: HASwitchPlate_AlarmCodeEntry_0
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[7].b[14]'
    payload: 'OFF'
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.haswitchplate_alarmcode1
      value: '{{ states.input_number.haswitchplate_alarmcode2.state }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.haswitchplate_alarmcode2
      value: '{{ states.input_number.haswitchplate_alarmcode3.state }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.haswitchplate_alarmcode3
      value: '{{ states.input_number.haswitchplate_alarmcode4.state }}'
  - service: input_number.set_value
    data:
      entity_id: input_number.haswitchplate_alarmcode4
      value: '0'

# Alarm panel is pending arm so update panel text
- alias: HASwitchPlate_AlarmStatus_Pending
  trigger:
  - platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: 'pending'
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[7].b[13].txt'
      payload: '"ARMING"'

# User is attempting to disarm the panel.  Send the alarm service our collected code then
# reset all the sliders.      
- alias: HASwitchPlate_Alarm_Disarm
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[7].b[15]'
    payload: 'OFF'
  condition: 
    condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: 'armed_away'
  action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.ha_alarm
    data_template:
      code: '{{ states.input_number.haswitchplate_alarmcode1.state|int }}{{ states.input_number.haswitchplate_alarmcode2.state|int }}{{ states.input_number.haswitchplate_alarmcode3.state|int }}{{ states.input_number.haswitchplate_alarmcode4.state|int }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.haswitchplate_alarmcode1
      value: '-1'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.haswitchplate_alarmcode2
      value: '-1'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.haswitchplate_alarmcode3
      value: '-1'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.haswitchplate_alarmcode4
      value: '-1'
      
# User is attempting to arm the panel.  Send the alarm service our collected code then
# reset all the sliders.
- alias: HASwitchPlate_Alarm_Arm
  trigger:
    platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[7].b[15]'
    payload: 'OFF'
  condition: 
    condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: 'disarmed'
  action:
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.ha_alarm
    data_template:
      code: '{{ states.input_number.haswitchplate_alarmcode1.state|int }}{{ states.input_number.haswitchplate_alarmcode2.state|int }}{{ states.input_number.haswitchplate_alarmcode3.state|int }}{{ states.input_number.haswitchplate_alarmcode4.state|int }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.haswitchplate_alarmcode1
      value: '-1'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.haswitchplate_alarmcode2
      value: '-1'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.haswitchplate_alarmcode3
      value: '-1'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.haswitchplate_alarmcode4
      value: '-1'
